# Generated by Django 2.1.3 on 2018-11-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printerbrand', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printermodel', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('lease_start', models.CharField(max_length=64)),
                ('lease_end', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('contract', models.CharField(max_length=64)),
                ('acconame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='printer.Acco')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='printer.Brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='printer.Model')),
            ],
        ),
    ]
